project:
  type: website
  output-dir: ../docs

website:
  title: "Lecture Notes -- EOSE10 Lecutre 8"
  navbar: false
  page-footer: "Disclaimer, parts of these notes were compiled with the help of ChatGPT."

format:
  pjk_theme-html:
    toc: true


